# Generated by Django 5.2 on 2026-04-25 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paise', models.BigIntegerField(help_text='Amount in paise (integer). 1 INR = 100 paise. Never a float.')),
                ('entry_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=6)),
                ('reference_id', models.UUIDField(blank=True, help_text='Links a DEBIT entry to its corresponding Payout UUID.', null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='merchants.merchant')),
            ],
            options={
                'db_table': 'ledger_entries',
                'indexes': [models.Index(fields=['merchant', 'created_at'], name='ledger_entr_merchan_491d5c_idx'), models.Index(fields=['reference_id'], name='ledger_entr_referen_1e9147_idx')],
            },
        ),
    ]
